-- 코드를 작성해주세요
SELECT E.ID, 
    CASE
        WHEN E.SIZE_GROUP = 4 THEN 'LOW'
        WHEN E.SIZE_GROUP = 3 THEN 'MEDIUM'
        WHEN E.SIZE_GROUP = 2 THEN 'HIGH'
        ELSE 'CRITICAL'
    END AS COLONY_NAME
FROM (
    SELECT  ID,
            NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE_GROUP
    FROM ECOLI_DATA
) E
ORDER BY E.ID;